/obj/structure/retail/clothing_store
	desc = "Purchase all the finest outfits.. Or don't wagie.."
	products_list = list(
		new /datum/data/vending_product("crimson red dress", /obj/item/clothing/under/darkpack/primogen_toreador/female	,	350),
		new /datum/data/vending_product("black dress", /obj/item/clothing/under/darkpack/business,	250),
		new /datum/data/vending_product("leather pants", /obj/item/clothing/under/darkpack/leatherpants,	200),
		new /datum/data/vending_product("fancy gray suit", /obj/item/clothing/under/darkpack/fancy_gray,	150),
		new /datum/data/vending_product("fancy red suit", /obj/item/clothing/under/darkpack/fancy_red,	150),
		new /datum/data/vending_product("black luxury suit", /obj/item/clothing/under/darkpack/ventrue,	50),
		new /datum/data/vending_product("black luxury suit skirt", /obj/item/clothing/under/darkpack/ventrue/female,	50),
		new /datum/data/vending_product("white buisness suit", /obj/item/clothing/under/darkpack/office,	50),
		new /datum/data/vending_product("black overcoat", /obj/item/clothing/under/darkpack/rich,	45),
		new /datum/data/vending_product("burgundy suit", /obj/item/clothing/under/darkpack/tremere,	35),
		new /datum/data/vending_product("burgundy suit skirt", /obj/item/clothing/under/darkpack/tremere/female,	35),
		new /datum/data/vending_product("plain black suit",	 /obj/item/clothing/under/darkpack/suit,	50),
		new /datum/data/vending_product("plain black suitskirt",	 /obj/item/clothing/under/darkpack/suit/female,	50),
		new /datum/data/vending_product("plain red suit",	 /obj/item/clothing/under/darkpack/sheriff,	80),
		new /datum/data/vending_product("plain red suitskirt",	 /obj/item/clothing/under/darkpack/sheriff/female,	80),
		new /datum/data/vending_product("plain blue suit",	 /obj/item/clothing/under/darkpack/clerk,	90),
		new /datum/data/vending_product("plain blue suitskirt",	 /obj/item/clothing/under/darkpack/clerk/female,	90),
		new /datum/data/vending_product("brown suit",	 /obj/item/clothing/under/darkpack/archivist,	60),
		new /datum/data/vending_product("brown suitskirt",	 /obj/item/clothing/under/darkpack/archivist/female,	60),
		new /datum/data/vending_product("flamboyant outfit", /obj/item/clothing/under/darkpack/toreador,	30),
		new /datum/data/vending_product("female flamboyant outfit", /obj/item/clothing/under/darkpack/toreador/female,	30),
		new /datum/data/vending_product("purple and black outfit", /obj/item/clothing/under/darkpack/sexy,	25),
		new /datum/data/vending_product("slick jacket", /obj/item/clothing/under/darkpack/slickback, 25),
		new /datum/data/vending_product("tracksuit", /obj/item/clothing/under/darkpack/sport,	25),
		new /datum/data/vending_product("grimey pants", /obj/item/clothing/under/darkpack/malkavian,	20),
		new /datum/data/vending_product("odd Goth schoolgirl attire", /obj/item/clothing/under/darkpack/malkavian/female,	20),
		new /datum/data/vending_product("gothic clothes", /obj/item/clothing/under/darkpack/gothic,	20),
		new /datum/data/vending_product("gothic attire", /obj/item/clothing/under/darkpack/brujah,	20),
		new /datum/data/vending_product("female punk attire ", /obj/item/clothing/under/darkpack/brujah/female,	20),
		new /datum/data/vending_product("pentagram shirt", /obj/item/clothing/under/darkpack/baali,	20),
		new /datum/data/vending_product("pentagram skirt", /obj/item/clothing/under/darkpack/baali/female,	20),
		new /datum/data/vending_product("punk outfit", /obj/item/clothing/under/darkpack/emo,	20),
		new /datum/data/vending_product("red hipster outfit", /obj/item/clothing/under/darkpack/red,	20),
		new /datum/data/vending_product("messy shirt", /obj/item/clothing/under/darkpack/bouncer,	15),
		new /datum/data/vending_product("blue overals", /obj/item/clothing/under/darkpack/mechanic,	20),
		new /datum/data/vending_product("black grunge outfit", /obj/item/clothing/under/darkpack/black,	20),
		new /datum/data/vending_product("gimp outfit", /obj/item/clothing/under/darkpack/nosferatu,	15),
		new /datum/data/vending_product("female gimp outfit", /obj/item/clothing/under/darkpack/nosferatu/female,	15),
		new /datum/data/vending_product("rugged attire", /obj/item/clothing/under/darkpack/gangrel,	15),
		new /datum/data/vending_product("female rugged attire", /obj/item/clothing/under/darkpack/gangrel/female,	15),
		new /datum/data/vending_product("yellow sleeveless shirt", /obj/item/clothing/under/darkpack/larry,	15),
		new /datum/data/vending_product("white sleeveless shirt", /obj/item/clothing/under/darkpack/bandit,	15),
		new /datum/data/vending_product("white turtleneck", /obj/item/clothing/under/darkpack/turtleneck_white,	15),
		new /datum/data/vending_product("black turtleneck", /obj/item/clothing/under/darkpack/turtleneck_black,	15),
		new /datum/data/vending_product("red turtleneck", /obj/item/clothing/under/darkpack/turtleneck_red,	15),
		new /datum/data/vending_product("navy turtleneck", /obj/item/clothing/under/darkpack/turtleneck_navy,	15),
		new /datum/data/vending_product("biker outfit", /obj/item/clothing/under/darkpack/biker,	15),
		new /datum/data/vending_product("burlesque outfit", /obj/item/clothing/under/darkpack/burlesque,	15),
		new /datum/data/vending_product("daisy dukes", /obj/item/clothing/under/darkpack/burlesque/daisyd,	10),
		new /datum/data/vending_product("black shoes", /obj/item/clothing/shoes/darkpack,	10),
		new /datum/data/vending_product("brown shoes", /obj/item/clothing/shoes/darkpack/brown,	10),
		new /datum/data/vending_product("white shoes", /obj/item/clothing/shoes/darkpack/white,	10),
		new /datum/data/vending_product("black boots", /obj/item/clothing/shoes/darkpack/jackboots,	10),
		new /datum/data/vending_product("work boots", /obj/item/clothing/shoes/darkpack/jackboots/work,	10),
		new /datum/data/vending_product("sneakers", /obj/item/clothing/shoes/darkpack/sneakers,	10),
		new /datum/data/vending_product("red sneakers", /obj/item/clothing/shoes/darkpack/sneakers/red,	10),
		new /datum/data/vending_product("high heels", /obj/item/clothing/shoes/darkpack/heels,	35),
		new /datum/data/vending_product("red high heels", /obj/item/clothing/shoes/darkpack/heels/red,	35),
		new /datum/data/vending_product("scaly shoes", /obj/item/clothing/shoes/darkpack/businessscaly,	35),
		new /datum/data/vending_product("black shoes", /obj/item/clothing/shoes/darkpack/businessblack,	35),
		new /datum/data/vending_product("metal tip shoes", /obj/item/clothing/shoes/darkpack/businesstip,	50),
		new /datum/data/vending_product("purple fur coat", /obj/item/clothing/suit/darkpack/slickbackcoat,	500),
		new /datum/data/vending_product("too much fancy jacket", /obj/item/clothing/suit/darkpack/majima_jacket,	100),
		new /datum/data/vending_product("labcoat", /obj/item/clothing/suit/darkpack/labcoat,	75),
		new /datum/data/vending_product("fancy gray jacket", /obj/item/clothing/suit/darkpack/fancy_gray,	50),
		new /datum/data/vending_product("fancy red jacket", /obj/item/clothing/suit/darkpack/fancy_red,	50),
		new /datum/data/vending_product("black trenchcoat", /obj/item/clothing/suit/darkpack/trench,	45),
		new /datum/data/vending_product("brown trenchcoat", /obj/item/clothing/suit/darkpack/trench/alt,	35),
		new /datum/data/vending_product("brown coat", /obj/item/clothing/suit/darkpack/coat,	15),
		new /datum/data/vending_product("green coat", /obj/item/clothing/suit/darkpack/coat/alt,	15),
		new /datum/data/vending_product("jacket", /obj/item/clothing/suit/darkpack/jacket,	15),
		new /datum/data/vending_product("black coat", /obj/item/clothing/suit/darkpack/coat/winter,	15),
		new /datum/data/vending_product("red coat", /obj/item/clothing/suit/darkpack/coat/winter/alt,	15),
		new /datum/data/vending_product("yellow aviators", /obj/item/clothing/glasses/darkpack/yellow,	20),
		new /datum/data/vending_product("red aviators", /obj/item/clothing/glasses/darkpack/red,	20),
		new /datum/data/vending_product("sunglasses", /obj/item/clothing/glasses/darkpack/sun,	20),
		new /datum/data/vending_product("prescription glasses", /obj/item/clothing/glasses/darkpack/perception,	20),
		new /datum/data/vending_product("leather gloves", /obj/item/clothing/gloves/darkpack/leather,	25),
		new /datum/data/vending_product("rubber gloves", /obj/item/clothing/gloves/darkpack/cleaning,	15),
		new /datum/data/vending_product("latex gloves", /obj/item/clothing/gloves/darkpack/latex,	5),
		new /datum/data/vending_product("black work gloves", /obj/item/clothing/gloves/darkpack/work,	45),
		new /datum/data/vending_product("bandana", /obj/item/clothing/head/darkpack/bandana,	10),
		new /datum/data/vending_product("red bandana", /obj/item/clothing/head/darkpack/bandana/red,	10),
		new /datum/data/vending_product("black bandana", /obj/item/clothing/head/darkpack/bandana/black,	10),
		new /datum/data/vending_product("baseball cap", /obj/item/clothing/head/darkpack/baseballcap, 10),
		new /datum/data/vending_product("ushanka", /obj/item/clothing/head/darkpack/ushanka, 20),
		new /datum/data/vending_product("beanie", /obj/item/clothing/head/darkpack/beanie,	10),
		new /datum/data/vending_product("black beanie", /obj/item/clothing/head/darkpack/beanie/black,	10),
		new /datum/data/vending_product("rough beanie", /obj/item/clothing/head/darkpack/beanie/homeless,	10),
		new /datum/data/vending_product("scarf", /obj/item/clothing/neck/darkpack/scarf,	10),
		new /datum/data/vending_product("red scarf", /obj/item/clothing/neck/darkpack/scarf/red,	10),
		new /datum/data/vending_product("blue scarf", /obj/item/clothing/neck/darkpack/scarf/blue,	10),
		new /datum/data/vending_product("green scarf", /obj/item/clothing/neck/darkpack/scarf/green,	10),
		new /datum/data/vending_product("white scarf", /obj/item/clothing/neck/darkpack/scarf/white,	10),
		new /datum/data/vending_product("cross", /obj/item/card/hunter, 25),
		new /datum/data/vending_product("duffelbag", /obj/item/storage/backpack/duffelbag,	100),
		new /datum/data/vending_product("backpack", /obj/item/storage/backpack, 100),
		new /datum/data/vending_product("satchel", /obj/item/storage/backpack/satchel, 100),
		new /datum/data/vending_product("leather satchel", /obj/item/storage/backpack/satchel/leather, 150),
							// REQUIEM EXAPNDED WARDROBE IMPORT STARTS HERE
		new /datum/data/mining_equipment("white veil",		/obj/item/clothing/glasses/darkpack/white_veil, 25 ),
		new /datum/data/mining_equipment("black veil", /obj/item/clothing/glasses/darkpack/black_veil, 25 ),
		new /datum/data/mining_equipment("brown cowboy hat", /obj/item/clothing/head/darkpack/cowboyhat, 20),
		new /datum/data/mining_equipment("black cowboy hat", /obj/item/clothing/head/darkpack/cowboy_black, 20),
		new /datum/data/mining_equipment("wide cowboy hat", /obj/item/clothing/head/darkpack/cowboy_wide, 20),
		new /datum/data/mining_equipment("white cowboy hat", /obj/item/clothing/head/darkpack/cowboy_white, 20),
		new /datum/data/mining_equipment("white wide cowboy hat", /obj/item/clothing/head/darkpack/cowboy_white_wide, 20),
		new /datum/data/mining_equipment("fuzzy monster hat", /obj/item/clothing/head/darkpack/fuzzy, 20),
		new /datum/data/mining_equipment("fez", /obj/item/clothing/head/darkpack/fez, 20),
		new /datum/data/mining_equipment("feathered hat", /obj/item/clothing/head/darkpack/feather_trilby, 20),
		new /datum/data/mining_equipment("fedora", /obj/item/clothing/head/darkpack/fedora, 20),
		new /datum/data/mining_equipment("mariner's cap", /obj/item/clothing/head/darkpack/mariner, 20),
		new /datum/data/mining_equipment("white peaked cap", /obj/item/clothing/head/darkpack/whitepeakcap, 20),
		new /datum/data/mining_equipment("biker cap", /obj/item/clothing/head/darkpack/biker, 20),
		new /datum/data/mining_equipment("captain's hat", /obj/item/clothing/head/darkpack/captain, 20),
		new /datum/data/mining_equipment("small cowboy hat", /obj/item/clothing/head/darkpack/cowboy_small, 20),
		new /datum/data/mining_equipment("aviator cap", /obj/item/clothing/head/darkpack/tank, 20),
		new /datum/data/mining_equipment("bucket hat", /obj/item/clothing/head/darkpack/buckethat, 20),
		new /datum/data/mining_equipment("beaver hat", /obj/item/clothing/head/darkpack/beaver_hat, 20),
		new /datum/data/mining_equipment("frilly headband", /obj/item/clothing/head/darkpack/frillyheadband, 20),
		new /datum/data/mining_equipment("black headdress", /obj/item/clothing/head/darkpack/black_headdress, 20),
		new /datum/data/mining_equipment("right eyepatch", /obj/item/clothing/glasses/darkpack/eyepatch, 15),
		new /datum/data/mining_equipment("left eyepatch", /obj/item/clothing/glasses/darkpack/eyepatch_alt, 15),
		new /datum/data/mining_equipment("medical eyepatch right", /obj/item/clothing/glasses/darkpack/eyepatch_white, 15),
		new /datum/data/mining_equipment("medical eyepatch left", /obj/item/clothing/glasses/darkpack/eyepatch_white_alt, 15),
		new /datum/data/mining_equipment("two-tone glasses", /obj/item/clothing/glasses/darkpack/threedee, 15),
		new /datum/data/mining_equipment("panama hat", /obj/item/clothing/head/darkpack/panama, 15),
		new /datum/data/mining_equipment("authentic maid dress", /obj/item/clothing/under/darkpack/maid, 60),
		new /datum/data/mining_equipment("prescription aviators", /obj/item/clothing/glasses/darkpack/metalframe, 20),
		new /datum/data/mining_equipment("green glasses", /obj/item/clothing/glasses/darkpack/green, 20),
		new /datum/data/mining_equipment("hipster glasses", /obj/item/clothing/glasses/darkpack/retro, 20),
		new /datum/data/mining_equipment("safety goggles", /obj/item/clothing/glasses/darkpack/safetygoggles, 20),
		new /datum/data/mining_equipment("big sunglasses", /obj/item/clothing/glasses/darkpack/bigsunglasses, 20),
		new /datum/data/mining_equipment("thin sunglasses", /obj/item/clothing/glasses/darkpack/thinsunglasses, 20),
		new /datum/data/mining_equipment("aviators", /obj/item/clothing/glasses/darkpack/aviator, 20),
		new /datum/data/mining_equipment("green aviators", /obj/item/clothing/glasses/darkpack/aviator_green, 20),
		new /datum/data/mining_equipment("blue aviators", /obj/item/clothing/glasses/darkpack/aviator_blue, 20),
		new /datum/data/mining_equipment("red aviators", /obj/item/clothing/glasses/darkpack/aviator_red, 20),
		new /datum/data/mining_equipment("black flats", /obj/item/clothing/shoes/darkpack/flats, 35),
		new /datum/data/mining_equipment("brown flats", /obj/item/clothing/shoes/darkpack/flats/brown, 35),
		new /datum/data/mining_equipment("white flats", /obj/item/clothing/shoes/darkpack/flats/white, 35),
		new /datum/data/mining_equipment("red flats", /obj/item/clothing/shoes/darkpack/flats/red, 35),
		new /datum/data/mining_equipment("orange flats", /obj/item/clothing/shoes/darkpack/flats/orange, 35),
		new /datum/data/mining_equipment("purple flats", /obj/item/clothing/shoes/darkpack/flats/purple, 35),
		new /datum/data/mining_equipment("blue flats", /obj/item/clothing/shoes/darkpack/flats/blue, 35),
		new /datum/data/mining_equipment("blue sneakers", /obj/item/clothing/shoes/darkpack/sneakers_blue, 15),
		new /datum/data/mining_equipment("dark red cap", /obj/item/clothing/head/darkpack/redsoft, 30),
		new /datum/data/mining_equipment("grey flatcap", /obj/item/clothing/head/darkpack/gent_cap, 30),
		new /datum/data/mining_equipment("black flatcap", /obj/item/clothing/head/darkpack/flatcap, 30),
		new /datum/data/mining_equipment("white flatcap", /obj/item/clothing/head/darkpack/flatcap/white, 30),
		new /datum/data/mining_equipment("grey beret", /obj/item/clothing/head/darkpack/beret_grey, 30),
		new /datum/data/mining_equipment("white beret", /obj/item/clothing/head/darkpack/beret_white, 30),
		new /datum/data/mining_equipment("green utility cap", /obj/item/clothing/head/darkpack/greenutil, 30),
		new /datum/data/mining_equipment("tan utility cap", /obj/item/clothing/head/darkpack/tanutil, 30),
		new /datum/data/mining_equipment("boater hat", /obj/item/clothing/head/darkpack/boater_hat, 30),
		new /datum/data/mining_equipment("wool hat", /obj/item/clothing/head/darkpack/woolhat, 30),
		new /datum/data/mining_equipment("blue wool hat", /obj/item/clothing/head/darkpack/woolhat_blue, 30),
		new /datum/data/mining_equipment("picture hat", /obj/item/clothing/head/darkpack/picture_hat, 30),
		new /datum/data/mining_equipment("red picture hat", /obj/item/clothing/head/darkpack/picture_red, 30),
		new /datum/data/mining_equipment("blue clipped tie", /obj/item/clothing/neck/darkpack/tie/blueclip, 15),
		new /datum/data/mining_equipment("long blue tie", /obj/item/clothing/neck/darkpack/tie/bluelong, 15),
		new /datum/data/mining_equipment("red clipped tie", /obj/item/clothing/neck/darkpack/tie/redclip, 15),
		new /datum/data/mining_equipment("long red tie", /obj/item/clothing/neck/darkpack/tie/redlong, 15),
		new /datum/data/mining_equipment("navy tie", /obj/item/clothing/neck/darkpack/tie/navy, 15),
		new /datum/data/mining_equipment("yellow tie", /obj/item/clothing/neck/darkpack/tie/yellow, 15),
		new /datum/data/mining_equipment("white tie", /obj/item/clothing/neck/darkpack/tie/white, 15),
		new /datum/data/mining_equipment("green tie", /obj/item/clothing/neck/darkpack/tie/darkgreen, 15),
		new /datum/data/mining_equipment("choker", /obj/item/clothing/neck/darkpack/choker, 30),
		new /datum/data/mining_equipment("silver choker", /obj/item/clothing/neck/darkpack/choker/silver, 30),
		new /datum/data/mining_equipment("ring choker", /obj/item/clothing/neck/darkpack/choker/collar, 30),
		new /datum/data/mining_equipment("steel choker", /obj/item/clothing/neck/darkpack/choker/collar/steel, 30),
		new /datum/data/mining_equipment("gold ring choker", /obj/item/clothing/neck/darkpack/choker/collar/leatherg, 30),
		new /datum/data/mining_equipment("blue suit jacket", /obj/item/clothing/suit/darkpack/toggle/suitjacket/blue, 45),
		new /datum/data/mining_equipment("purple suit jacket", /obj/item/clothing/suit/darkpack/toggle/suitjacket/purple, 45),
		new /datum/data/mining_equipment("black suit jacket", /obj/item/clothing/suit/darkpack/toggle/suitjacket/black, 45),
		new /datum/data/mining_equipment("black leather jacket", /obj/item/clothing/suit/darkpack/toggle/leather, 45),
		new /datum/data/mining_equipment("brown leather jacket", /obj/item/clothing/suit/darkpack/toggle/leather_brown, 45),
		new /datum/data/mining_equipment("black leather vest", /obj/item/clothing/suit/darkpack/toggle/leather_sleeveless, 45),
		new /datum/data/mining_equipment("brown leather vest", /obj/item/clothing/suit/darkpack/toggle/leather_brown_sleeveless, 45),
		new /datum/data/mining_equipment("grey zipper hoodie", /obj/item/clothing/suit/darkpack/toggle/hoodie_grey, 45),
		new /datum/data/mining_equipment("black zipper hoodie", /obj/item/clothing/suit/darkpack/toggle/hoodie_black, 45),
		new /datum/data/mining_equipment("red zipper hoodie", /obj/item/clothing/suit/darkpack/toggle/hoodie_red, 45),
		new /datum/data/mining_equipment("blue zipper hoodie", /obj/item/clothing/suit/darkpack/toggle/hoodie_blue, 45),
		new /datum/data/mining_equipment("orange zipper hoodie", /obj/item/clothing/suit/darkpack/toggle/hoodie_orange, 45),
		new /datum/data/mining_equipment("pink zipper hoodie", /obj/item/clothing/suit/darkpack/toggle/hoodie_pink, 45),
		new /datum/data/mining_equipment("black track jacket", /obj/item/clothing/suit/darkpack/toggle/trackjacket, 45),
		new /datum/data/mining_equipment("blue track jacket", /obj/item/clothing/suit/darkpack/toggle/trackjacketblue, 45),
		new /datum/data/mining_equipment("green track jacket", /obj/item/clothing/suit/darkpack/toggle/trackjacketgreen, 45),
		new /datum/data/mining_equipment("red track jacket", /obj/item/clothing/suit/darkpack/toggle/trackjacketred, 45),
		new /datum/data/mining_equipment("white track jacket", /obj/item/clothing/suit/darkpack/toggle/trackjacketwhite, 45),
		new /datum/data/mining_equipment("yellow fur-lined jacket", /obj/item/clothing/suit/darkpack/toggle/yellow_dep_jacket, 45),
		new /datum/data/mining_equipment("red fur-lined jacket", /obj/item/clothing/suit/darkpack/toggle/red_dep_jacket, 45),
		new /datum/data/mining_equipment("white fur-lined jacket", /obj/item/clothing/suit/darkpack/toggle/white_dep_jacket, 45),
		new /datum/data/mining_equipment("brown fur-lined jacket", /obj/item/clothing/suit/darkpack/toggle/brown_dep_jacket, 45),
		new /datum/data/mining_equipment("grey fur-linked jacket", /obj/item/clothing/suit/darkpack/toggle/grey_dep_jacket, 45),
		new /datum/data/mining_equipment("blue fur-lined jacket", /obj/item/clothing/suit/darkpack/toggle/blue_dep_jacket, 45),
		new /datum/data/mining_equipment("bomber jacket", /obj/item/clothing/suit/darkpack/toggle/bomber, 45),
		new /datum/data/mining_equipment("asymmetrical bomber jacket", /obj/item/clothing/suit/darkpack/toggle/retro_bomber, 45),
		new /datum/data/mining_equipment("grey flannel shirt", /obj/item/clothing/suit/darkpack/flannel, 45),
		new /datum/data/mining_equipment("red flannel shirt", /obj/item/clothing/suit/darkpack/flannel/red, 45),
		new /datum/data/mining_equipment("aqua flannel shirt", /obj/item/clothing/suit/darkpack/flannel/aqua, 45),
		new /datum/data/mining_equipment("brown flannel shirt", /obj/item/clothing/suit/darkpack/flannel/brown, 45),
		new /datum/data/mining_equipment("letterman jacket,  ULCA", /obj/item/clothing/suit/darkpack/letterman_c, 45),
		new /datum/data/mining_equipment("black letterman jacket", /obj/item/clothing/suit/darkpack/letterman_black, 45),
		new /datum/data/mining_equipment("purple letterman jacket", /obj/item/clothing/suit/darkpack/letterman_purple, 45),
		new /datum/data/mining_equipment("white canvas jacket", /obj/item/clothing/suit/darkpack/military_white, 45),
		new /datum/data/mining_equipment("tan canvas jacket", /obj/item/clothing/suit/darkpack/military_tan, 45),
		new /datum/data/mining_equipment("navy canvas jacket", /obj/item/clothing/suit/darkpack/military_navy, 45),
		new /datum/data/mining_equipment("gray canvas jacket", /obj/item/clothing/suit/darkpack/military_grey, 45),
		new /datum/data/mining_equipment("black canvas jacket", /obj/item/clothing/suit/darkpack/military_black, 45),
		new /datum/data/mining_equipment("yellow parka", /obj/item/clothing/suit/hooded/hoodie/parka_yellow, 45),
		new /datum/data/mining_equipment("red parka", /obj/item/clothing/suit/hooded/hoodie/parka_red, 45),
		new /datum/data/mining_equipment("purple parka", /obj/item/clothing/suit/hooded/hoodie/parka_purple, 45),
		new /datum/data/mining_equipment("green parka", /obj/item/clothing/suit/hooded/hoodie/parka_green, 45),
		new /datum/data/mining_equipment("blue parka", /obj/item/clothing/suit/hooded/hoodie/parka_blue, 45),
		new /datum/data/mining_equipment("vintage parka", /obj/item/clothing/suit/hooded/hoodie/parka_vintage, 45),
		new /datum/data/mining_equipment("high-waisted trousers", /obj/item/clothing/under/darkpack/hightrousers, 50),
		new /datum/data/mining_equipment("high-waisted skirt", /obj/item/clothing/under/darkpack/highskirt, 50),
		new /datum/data/mining_equipment("ripped punk jeans", /obj/item/clothing/under/darkpack/rippedpunk, 50),
		new /datum/data/mining_equipment("grey suit slacks", /obj/item/clothing/under/darkpack/suitslacks, 35),
		new /datum/data/mining_equipment("white shirt and waistcoat", /obj/item/clothing/under/darkpack/suit/waistcoat, 35),
		new /datum/data/mining_equipment("tan dress shirt", /obj/item/clothing/under/darkpack/suit/tanshirt, 35),
		new /datum/data/mining_equipment("tan shirt and waistcoat", /obj/item/clothing/under/darkpack/suit/tanshirtwaistcoat, 35),
		new /datum/data/mining_equipment("grey suit skirt", /obj/item/clothing/under/darkpack/suit/greyskirt, 35),
		new /datum/data/mining_equipment("black suit slacks",/obj/item/clothing/under/darkpack/suit/black, 35),
		new /datum/data/mining_equipment("black suit skirt", /obj/item/clothing/under/darkpack/suit/blackskirt, 50),
		new /datum/data/mining_equipment("purple suit slacks", /obj/item/clothing/under/darkpack/suit/purple, 35),
		new /datum/data/mining_equipment("charcoal suit slacks", /obj/item/clothing/under/darkpack/suit/charcoal, 35),
		new /datum/data/mining_equipment("navy suit slacks", /obj/item/clothing/under/darkpack/suit/navy, 35),
		new /datum/data/mining_equipment("burgundy suit slacks", /obj/item/clothing/under/darkpack/suit/burgundy, 35),
		new /datum/data/mining_equipment("blue suit slacks", /obj/item/clothing/under/darkpack/suit/blue, 35),
		new /datum/data/mining_equipment("checkered suit slacks", /obj/item/clothing/under/darkpack/suit/checkered, 35),
		new /datum/data/mining_equipment("tan suit slacks", /obj/item/clothing/under/darkpack/suit/tan, 35),
		new /datum/data/mining_equipment("purple suit skirt", /obj/item/clothing/under/darkpack/suit/purpleskirt, 35),
		new /datum/data/mining_equipment("charcoal suit skirt", /obj/item/clothing/under/darkpack/suit/charcoalskirt, 35),
		new /datum/data/mining_equipment("navy suit skirt", /obj/item/clothing/under/darkpack/suit/navyskirt, 35),
		new /datum/data/mining_equipment("burgundy suit skirt", /obj/item/clothing/under/darkpack/suit/burgundyskirt, 35),
		new /datum/data/mining_equipment("blue suit skirt", /obj/item/clothing/under/darkpack/suit/blueskirt, 35),
		new /datum/data/mining_equipment("checkered suit skirt", /obj/item/clothing/under/darkpack/suit/checkeredskirt, 35),
		new /datum/data/mining_equipment("tan suit skirt", /obj/item/clothing/under/darkpack/suit/tanskirt, 35),
		new /datum/data/mining_equipment("black pantsuit", /obj/item/clothing/under/darkpack/suit/blackfem, 100),
		new /datum/data/mining_equipment("corset and skirt outfit", /obj/item/clothing/under/darkpack/dress/black_corset, 75),
		new /datum/data/mining_equipment("fancy red dress", /obj/item/clothing/under/darkpack/dress/darkred, 75),
		new /datum/data/mining_equipment("red skirt", /obj/item/clothing/under/darkpack/skirt/outfit, 35),
		new /datum/data/mining_equipment("blue plaid skirt", /obj/item/clothing/under/darkpack/skirt/outfit/plaid_blue, 35),
		new /datum/data/mining_equipment("red plaid skirt", /obj/item/clothing/under/darkpack/skirt/outfit/plaid_red, 35),
		new /datum/data/mining_equipment("purple plaid skirt", /obj/item/clothing/under/darkpack/skirt/outfit/plaid_purple, 35),
		new /datum/data/mining_equipment("pentagram dress", /obj/item/clothing/under/darkpack/dress/pentagram, 35),
		new /datum/data/mining_equipment("little black dress", /obj/item/clothing/under/darkpack/dress/littleblackdress, 35),
		new /datum/data/mining_equipment("yellow swoop dress", /obj/item/clothing/under/darkpack/dress/yellowswoop, 90),
		new /datum/data/mining_equipment("black tango dress", /obj/item/clothing/under/darkpack/dress/blacktango, 35),
		new /datum/data/mining_equipment("slim qipao", /obj/item/clothing/under/darkpack/dress/qipao2, 150),
		new /datum/data/mining_equipment("striped dress", /obj/item/clothing/under/darkpack/dress/stripeddress, 35),
		new /datum/data/mining_equipment("sailor dress", /obj/item/clothing/under/darkpack/dress/sailordress, 35),
		new /datum/data/mining_equipment("frilly black dress", /obj/item/clothing/under/darkpack/dress/blackfrilly, 75),
		new /datum/data/mining_equipment("white lace dress", /obj/item/clothing/under/darkpack/dress/wedding_gothic, 150),
		new /datum/data/mining_equipment("witchy dress", /obj/item/clothing/under/darkpack/dress/old_wench_dress, 100),
		new /datum/data/mining_equipment("countess dress", /obj/item/clothing/under/darkpack/dress/countess, 150),
		new /datum/data/mining_equipment("silk goddess dress", /obj/item/clothing/under/darkpack/dress/goddess, 150),
		new /datum/data/mining_equipment("monochrome lace dress", /obj/item/clothing/under/darkpack/dress/white_dress, 150),
		new /datum/data/mining_equipment("gold embroidered black dress", /obj/item/clothing/under/darkpack/dress/sermon, 150),
		new /datum/data/mining_equipment("chain dress", /obj/item/clothing/under/darkpack/dress/chain, 150),
		new /datum/data/mining_equipment("modest dress", /obj/item/clothing/under/darkpack/dress/modest, 75),
		new /datum/data/mining_equipment("skater cargo pants", /obj/item/clothing/under/darkpack/skater_boy, 75),
		new /datum/data/mining_equipment("skater skirt", /obj/item/clothing/under/darkpack/skater_skirt, 75),
		new /datum/data/mining_equipment("strawberry lolita dress", /obj/item/clothing/under/darkpack/dress/strawberrylolita, 150),
		new /datum/data/mining_equipment("widows dress", /obj/item/clothing/under/darkpack/dress/matron, 150),
		new /datum/data/mining_equipment("little gothic dress", /obj/item/clothing/under/darkpack/dress/maiden, 150),
		new /datum/data/mining_equipment("open front silk shirt", /obj/item/clothing/under/darkpack/novella, 150),
		new /datum/data/mining_equipment("sheer black lace dress", /obj/item/clothing/under/darkpack/dress/laceblack, 150),
		new /datum/data/mining_equipment("royal red suit", /obj/item/clothing/under/darkpack/royalredsuit, 150),
		new /datum/data/mining_equipment("dark band t-shirt", /obj/item/clothing/under/darkpack/bandshirt_dark, 35),
		new /datum/data/mining_equipment("light band t-shirt", /obj/item/clothing/under/darkpack/bandshirt_light, 35),
		new /datum/data/mining_equipment("grey suspenders and trousers", /obj/item/clothing/under/darkpack/suspenders, 35),
		new /datum/data/mining_equipment("black suspenders and trousers", /obj/item/clothing/under/darkpack/suspenders_fancy, 35),
		new /datum/data/mining_equipment("red button-up", /obj/item/clothing/under/darkpack/buttonup_red, 35),
		new /datum/data/mining_equipment("black baggy pants", /obj/item/clothing/under/darkpack/pants/baggy, 35),
		new /datum/data/mining_equipment("black jeans", /obj/item/clothing/under/darkpack/pants/blackjeans, 35),
		new /datum/data/mining_equipment("baggy black jeans", /obj/item/clothing/under/darkpack/pants/blackjeansbaggy, 35),
		new /datum/data/mining_equipment("ripped black jeans", /obj/item/clothing/under/darkpack/pants/blackjeansripped, 35),
		new /datum/data/mining_equipment("grey jeans", /obj/item/clothing/under/darkpack/pants/greyjeans, 35),
		new /datum/data/mining_equipment("baggy grey jeans", /obj/item/clothing/under/darkpack/pants/greyjeansbaggy, 35),
		new /datum/data/mining_equipment("ripped grey jeans", /obj/item/clothing/under/darkpack/pants/greyjeansripped, 35),
		new /datum/data/mining_equipment("baggy classic jeans", /obj/item/clothing/under/darkpack/pants/bluejeansbaggy, 35),
		new /datum/data/mining_equipment("ripped blue jeans", /obj/item/clothing/under/darkpack/pants/bluejeansripped, 35),
		new /datum/data/mining_equipment("stonewashed jeans", /obj/item/clothing/under/darkpack/pants/mustangjeans, 35),
		new /datum/data/mining_equipment("baggy stonewashed jeans", /obj/item/clothing/under/darkpack/pants/mustangjeansbaggy, 35),
		new /datum/data/mining_equipment("ripped stonewashed jeans", /obj/item/clothing/under/darkpack/pants/mustangjeansripped, 35),
		new /datum/data/mining_equipment("baggy camo pants", /obj/item/clothing/under/darkpack/pants/camobaggy, 35),
		new /datum/data/mining_equipment("white pants", /obj/item/clothing/under/darkpack/pants/white, 35),
		new /datum/data/mining_equipment("baggy white pants", /obj/item/clothing/under/darkpack/pants/whitebaggy, 35),
		new /datum/data/mining_equipment("red pants", /obj/item/clothing/under/darkpack/pants/red, 35),
		new /datum/data/mining_equipment("baggy red pants", /obj/item/clothing/under/darkpack/pants/redbaggy, 35),
		new /datum/data/mining_equipment("khaki pants", /obj/item/clothing/under/darkpack/pants/khaki, 35),
		new /datum/data/mining_equipment("baggy khaki pants", /obj/item/clothing/under/darkpack/pants/khakibaggy, 35),
		new /datum/data/mining_equipment("blue trackpants", /obj/item/clothing/under/darkpack/pants/trackpants/blue, 35),
		new /datum/data/mining_equipment("green trackpants", /obj/item/clothing/under/darkpack/pants/trackpants/green, 35),
		new /datum/data/mining_equipment("red trackpants", /obj/item/clothing/under/darkpack/pants/trackpants/red, 35),
		new /datum/data/mining_equipment("white trackpants", /obj/item/clothing/under/darkpack/pants/trackpants/white, 35),
		new /datum/data/mining_equipment("black jeans shorts", /obj/item/clothing/under/darkpack/shorts, 35),
		new /datum/data/mining_equipment("black jean shorts shorts", /obj/item/clothing/under/darkpack/shorts/blackshortshort, 35),
		new /datum/data/mining_equipment("blue jean shorts", /obj/item/clothing/under/darkpack/shorts/jeanshorts, 35),
		new /datum/data/mining_equipment("blue jean short shorts", /obj/item/clothing/under/darkpack/shorts/jeanshortshort, 35),
		new /datum/data/mining_equipment("stonewashed jean shorts", /obj/item/clothing/under/darkpack/shorts/mustangjeanshorts, 35),
		new /datum/data/mining_equipment("stonewashed jean short shorts", /obj/item/clothing/under/darkpack/shorts/mustangjeanshortshort, 35),
		new /datum/data/mining_equipment("khaki shorts", /obj/item/clothing/under/darkpack/shorts/khaki, 35),
		new /datum/data/mining_equipment("black leather skirt", /obj/item/clothing/under/darkpack/shorts/skirt, 35),
		new /datum/data/mining_equipment("short denim skirt", /obj/item/clothing/under/darkpack/shorts/skirtdenim, 35),
		new /datum/data/mining_equipment("white widows dress", /obj/item/clothing/under/darkpack/dress/matron_white, 150),
		new /datum/data/mining_equipment("pinup skirt", /obj/item/clothing/under/darkpack/pinup, 150),
		new /datum/data/mining_equipment("white shawl", /obj/item/clothing/suit/darkpack/shawl_white, 50),
						 // REQUIEM EXPANDED WARDROBE IMPORT ENDS HERE
	)
